<script setup>
import resultDemo from './assets/demo.gif'
import resultStill from './assets/items.jpg'
import crosshairShot from './assets/crosshair.jpg'
import buildingShot from './assets/building.jpg'
import architectureDiagram from './assets/arch.jpg'
import raymarchingDiagram from './assets/raymarching.jpg'
import pipelineDiagram from './assets/pipeline.jpg'
import noBufferShot from './assets/nobuffer.jpg'
import bufferDiagram from './assets/buffers.jpg'
import gamepadPhoto from './assets/gamepad.jpg'
import ProjectCodeBlock from '../../components/ProjectCodeBlock.vue'
</script>

<template>
    <div class="project-article fmcpga-article">
        <section class="project-article__section">
            <p class="detail-text">
                <strong>Features.</strong> This project is a Minecraft-like voxel renderer implemented directly in VHDL on Artix-7 FPGA, with real scene traversal, texture lookup, block placement and destruction, transparent blocks, PS/2 gamepad control, and VGA output.
            </p>
            <p class="detail-text">
                <strong>Stack.</strong> VHDL 2008, Vivado 2022.2, fixed-point / integer arithmetic, BRAM storage, a rendering pipeline, double-buffered display, and PS/2 gamepad interface.
            </p>
        </section>

        <section class="project-article__section">
            <h2>Demonstration</h2>
            <p>
                The project runs as an interactive scene on FPGA, with the whole image generated by the hardware pipeline and then pushed out through VGA.
            </p>
            <figure class="project-media project-media--medium">
                <img :src="resultDemo" alt="FmcPGA running on FPGA hardware" />
                <figcaption>A short hardware demo of the final system running on the board, played with a gamepad.</figcaption>
            </figure>
            <div class="project-media-grid project-media-grid--three">
                <figure class="project-media">
                    <img :src="resultStill" alt="FmcPGA item selection screenshot" />
                    <figcaption>Item selection and textured voxel scene.</figcaption>
                </figure>
                <figure class="project-media">
                    <img :src="crosshairShot" alt="FmcPGA crosshair highlight screenshot" />
                    <figcaption>Crosshair-based selection and highlight.</figcaption>
                </figure>
                <figure class="project-media">
                    <img :src="buildingShot" alt="FmcPGA building screenshot" />
                    <figcaption>Placement and destruction in the live scene.</figcaption>
                </figure>
            </div>
        </section>

        <section class="project-article__section">
            <h2>System overview</h2>
            <p>
                At the top level, I split the design into three parts: the rendering pipeline, the player-state / interaction logic, and the display path. The renderer is fed with the player pose and scene data; the player-state logic updates movement, item switching, and block operations at frame boundaries; the display side reads from the front buffer while the pipeline writes the next frame into the back buffer.
            </p>
            <figure class="project-media project-media--medium">
                <img :src="architectureDiagram" alt="FmcPGA architecture diagram" />
                <figcaption>The project is organized around a rendering pipeline, a player-state path, and a separated display path.</figcaption>
            </figure>
        </section>

        <section class="project-article__section">
            <h2>Ray marching</h2>
            <p>
                For a voxel scene, rasterizing arbitrary meshes would have made the hardware much heavier than necessary. Here every object is axis-aligned and the world, so I can just consider which block will a ray starting from the eye position enter next, and when to stop.
            </p>
            <p>
                That is why the renderer is built around ray marching. A ray starts from the current view point, advances block by block, checks the next axis crossing, reads the block type, and either keeps going or samples texture color on the intersected face. Transparent blocks are handled by keeping an accumulated RGBA color and continuing until opacity is saturated or the ray exits into the sky.
            </p>
            <figure class="project-media project-media--portrait">
                <img :src="raymarchingDiagram" alt="Ray marching diagram used by FmcPGA" />
                <figcaption>The renderer advances rays through the voxel map one block at a time instead of rasterizing arbitrary geometry.</figcaption>
            </figure>
            <p>
                All of this is integer-based. Even though the final board output is only 12-bit RGB, the internal pipeline keeps a higher-precision color representation during blending and only downsamples at the display writeback stage. This was necessary because transparent blocks look noticeably worse with the low internal precision.
            </p>
        </section>

        <section class="project-article__section">
            <h2>The rendering pipeline</h2>
            <p>
                Once the traversal rule is fixed, the renderer becomes a large combinational datapath. Then we can pipeline this datapath to improve the throughput.
            </p>
            <p>
                The final version uses ten stages for the core rendering flow, not counting the later image post-processing. One important detail here is that the expensive part is not the block lookup itself, but the division-heavy coordinate update around the fourth stage. I relied on Vivado divider IP there, and that stage became the practical frequency bottleneck of the whole design.
            </p>
            <p>
                The problem was that I didn't know how to generate a divider with latencies at that time. If redo it now, the performance can be significantly improved, for example, directly use my project <a href="#/projects/nodalhdl">NodalHDL</a> to generate the pipeline.
            </p>
            <figure class="project-media project-media--medium">
                <img :src="pipelineDiagram" alt="FmcPGA rendering pipeline diagram" />
                <figcaption>The final renderer is organized as a 10-stage pipeline around traversal, texture fetch, and color accumulation.</figcaption>
            </figure>
            <p>
                At 320×240 and 50 MHz pipeline clock, this architecture is already enough to produce smooth motion in the normal gameplay view. In the measurements I kept in the report, a horizontal view lands around 20 to 30 fps, sky view is roughly 15 fps, and degenerate cases with very short traversal can run much faster.
            </p>
        </section>

        <section class="project-article__section">
            <h2>Frame buffers</h2>
            <p>
                Rendering the image was only half the problem. The other half was moving frames between the pipeline clock domain and the VGA scanout path without visible corruption. Early during development I had a version without proper front/back isolation, and the result was exactly what the hardware timing suggested: stripes and visible frame misalignment.
            </p>
            <div class="project-media-grid project-media-grid--two">
                <figure class="project-media">
                    <img :src="noBufferShot" alt="Display artifact without double buffering in FmcPGA" />
                    <figcaption>An older version without proper buffer separation showed read/write conflicts directly on screen.</figcaption>
                </figure>
                <figure class="project-media">
                    <img :src="bufferDiagram" alt="Double-buffer display structure in FmcPGA" />
                    <figcaption>The final display path uses two BRAM-backed frame buffers and swaps them only at frame boundaries.</figcaption>
                </figure>
            </div>
            <p>
                The fix was straightforward in concept and absolutely necessary in practice: keep one BRAM buffer for reading and one for writing, then swap them synchronously only when the current frame finishes. On top of that, I added a short post-tracing path for crosshair inversion and selected-block highlighting before pixels are committed to the display buffer.
            </p>
        </section>

        <section class="project-article__section">
            <h2>Interaction</h2>
            <p>
                I used a PlayStation 2 gamepad through an SPI-like interface. It is used to keep player pose, select block, change inventory state, and modify the scene.
            </p>
            <figure class="project-media project-media--small">
                <img :src="gamepadPhoto" alt="PS2 gamepad used by FmcPGA" />
                <figcaption>The final setup used a PS2 gamepad as the practical control path for movement and interaction.</figcaption>
            </figure>
        </section>

        <section class="project-article__section">
            <h2>Discussion</h2>
            <p>
                The final design is already a compromise between visual completeness and FPGA reality. I reduced the display resolution to 320×240, kept the math in integers, and reused resources through the pipeline instead of trying to parallelize everything spatially. According to the implementation results I kept, the design sat roughly around 30% LUT, 65% BRAM, and 30% DSP on the xc7a100t part.
            </p>
            <p>
                The main remaining bottleneck is still the division-heavy part of the traversal update. And in fact this can be solved simply now.
            </p>
        </section>
    </div>
</template>
